# routers/report.py
"""
/api/report/generate – creates the one‑page executive PDF on the fly and streams it back.
The PDF is generated by `analytics_engine.generate_executive_report`.
A temporary file is used so the endpoint is stateless and safe for concurrent calls.
"""

import os
import tempfile
from fastapi import APIRouter
from fastapi.responses import FileResponse
from analytics_engine import generate_executive_report

router = APIRouter()


@router.get(
    "/report/generate",
    summary="Generate and download the executive PDF report",
    responses={200: {"content": {"application/pdf": {}}}},
)
def generate_report():
    # Create a temporary file that will be automatically cleaned up.
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf_path = tmp.name

    # The analytics module writes the PDF to the supplied path.
    generate_executive_report(pdf_path)

    # Ensure the file exists before streaming.
    if not os.path.exists(pdf_path):
        raise RuntimeError("PDF generation failed – file not created")

    # Stream the file back to the client. `FileResponse` will set the correct MIME type.
    return FileResponse(
        pdf_path,
        media_type="application/pdf",
        filename="executive_report.pdf",
        # FastAPI will close the file after response; optional cleanup can be added.
    )
